### ISSUE TITLE
Correct repository of the website

### ISSUE THREAD

**Issue by palnabarun** [marsiitr/marsiitr.github.io#1]
I see that the website is made in Jekyll. If you are planning to use Github Pages to host the website, shouldn't the code reside in the `marsiitr.github.io` repository?

**Comment by agshubhs** [comment]
Actually, we are planning to use subdomain of IITR website. And Regarding this we have talked in ICC  and soon we get the subdomain then it will run on **mars.iitr.ac.in**.

**Comment by palnabarun** [comment]
It is okay even if it is visible to the outside world on `mars.iitr.ac.in`. I don't think they will be hosting the site. We need to host and this can be done on `marsiitr.github.io`.

Keep me in loop when we get the subdomain.

**Comment by agshubhs** [comment]
Ok, iwill inform you as soon as we get the subdomain and  will also try it to shift it on ` marsiitr.github.io`

**Comment by agshubhs** [comment]
I have changed the working directory of the repository and now it is name is correct.

**Comment by palnabarun** [comment]
Cool. Thanks.

Closing this.
