### ISSUE TITLE
Order of the navigation header

### ISSUE THREAD

**Issue by palnabarun** [marsiitr/marsiitr.github.io#2]
Shouldn't the order of the navigation be the below one?
- Home
- About Us
- Projects (instead of Portfolio)
- Blog
- Team

**Comment by agshubhs** [comment]
Blog page is the Home page itself.  
I also want that the order should be like that but there is some issue in the code which I am trying to resolve due to which team page automatically comes first in the navigation bar.

**Comment by palnabarun** [comment]
> Blog page is the Home page itself.

No. Blog should be different from Home page. Home page should give brief insights about the group, some featured blogs, information about upcoming events etc.

**Comment by agshubhs** [comment]
@palnabarun  The order of pages in the navigation bar has been changed. Please review it.

**Comment by palnabarun** [comment]
Good Work.
