### ISSUE TITLE
Enable comments using disqus

### ISSUE THREAD

**Issue by palnabarun** [marsiitr/marsiitr.github.io#3]
- [x] Create an account on Disqus
- [x] Verify the account
- [x] Add the disqus shortname to `_config.yml`

**Comment by agshubhs** [comment]
Ok, I will do that. I will make an account on Disqus and enable comments on the website

**Comment by agshubhs** [comment]
Issue resolved Disquss comment section is added

**Comment by agshubhs** [comment]
@palnabarun please review it and let me know if further changes are needed. Otherwise, close the issue.

**Comment by palnabarun** [comment]
Looks good to me.

Thank you.
