### ISSUE TITLE
Remove tags from the pages

### ISSUE THREAD

**Issue by palnabarun** [marsiitr/marsiitr.github.io#4]
Tags should be present only in the blogs and not on content pages like `Gallery`, `Home`, `Team`, `About`.

**Comment by agshubhs** [comment]
I will resolve it.

**Comment by agshubhs** [comment]
I have removed the tags and add some tags to blogs.
Please review and if it is ok then close the issue.

**Comment by palnabarun** [comment]
It looks nice.

Thanks.
